FROM jolielang/jolie-docker-deployer
MAINTAINER Claudio Guidi <guidiclaudio@gmail.com>
COPY router_admin router_admin
COPY tools tools
COPY webapp webapp
COPY __router.ol __router.ol
COPY dependencies.iol dependencies.iol
COPY locations.iol locations.iol
COPY router.iol router.iol
COPY router.ol main.ol
EXPOSE 9080
EXPOSE 9081
EXPOSE 9082
